name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.15.3
      uses: actions/setup-node@v1
      with:
        node-version: 10.15.3
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn run build
      env:
        CI: true
